name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@master
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.15
      with:
        name: cryptodevtrader/docker-telegram-notifier/docker-telegram-notifier
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
